### ISSUE TITLE
Address use of "ignore-errors: true" in install-derived-app-bundle.yml

### ISSUE THREAD

**Issue by jscarsdale1** [greg-ses/simpleui#11]
Setting ignore_errors: true on the archival of the previous deployment risks breaking the existing deployment if the current deployment fails. 

Would be preferable to configure a "force" flag with a default of "false" for ignore_errors.

Need to figure out link-related errors which may occur which can lead to errors and inability to deploy an update.

**Comment by zbeucler-largo** [comment]
closed because no longer relevant
