### ISSUE TITLE
Fix resource leaks and unwind complexity in app-tab-overlay feature

### ISSUE THREAD

**Issue by jscarsdale1** [greg-ses/simpleui#21]
The overlay pages have significant memory and resource leaks and excessive CPU consumption.

- [ ] Research and correct memory leaks.
- [ ] Examine if there's an issue with animated gifs and refactor into css classes (or other) if there's a problem.
- [ ] Unwind obsolete drag and drop features.
- [ ] Move transformations that can be made in advance from client-side javascript in `base_app` into `simpleui-server`.

**Comment by zbeucler-largo** [comment]
memory leak in overlay tab fixed
